# Dependencies

# Permalinks
permalink:        pretty


# Setup
title:            Project Name
tagline:          ''
description:      'Project Description' 
url:              "https://anne-m-burton.github.io"
baseurl:          "/course-template-temp"


paginate:         5

# Custom vars
version:          0.0.0

github:
  repo:           https://github.com/anne-m-burton.github.io/course-template-temp
